// ==========================================
// TAUNTS.JS - KHO DỮ LIỆU CÂU THOẠI CHÀO SÂN & CHỌC TỨC
// ==========================================

window.TAUNT_POOL = [
    // --- NHÓM 1: VÕ THUẬT CỔ TRUYỀN & KHÍ CÔNG ---
    "Hạc Tấn Thiếu Lâm! Thủ thế! 🦩",
    "Mãnh Hổ Xuất Sơn! Biến sắc! 🐅",
    "Vịnh Xuân Quyền: Đại sư xuống núi! 🥊",
    "La Hán Thần Quyền! Kim cang hạ thế! 🧘",
    "Thái Cực Quyền - Dĩ Nhu Khắc Cương! ☯️",
    "Tuyệt kỹ: Khinh Công Đạp Tuyết Tầm Mai! 🍃",
    "Thiết Sa Chưởng - Vạn phát xuyên tâm! ✋",
    "Kim Cang Bất Hoại Thể! Đao thương bất nhập! 🛡️",
    "Túy Quyền - Túy tửu bộ pháp! Say mà tỉnh! 🍶",
    "Long Trảo Thủ! Xé toạc hư không! 🐉",
    "Bát Cực Quyền - Chấn thiên địa! 💥",
    "Hàng Long Thập Bát Chưởng! Long ngâm! 🐉",
    "Như Lai Thần Chưởng từ trên trời rơi xuống! 🖐️",
    "Độc Cô Cửu Kiếm - Phá kiếm thức! ⚔️",
    "Quỳ Hoa Bảo Điển - Tốc độ tối thượng! 🧭",
    
    // --- NHÓM 2: BIỂU DIỄN VÀ CÁC ĐIỆU NHẢY HUYỀN THOẠI ---
    "Moonwalk lướt mượt mà kiểu Michael Jackson! 🕺",
    "Nhảy Floss Dance chọc tức đối thủ! 🤙",
    "Múa quạt khởi động, nhạc lên là quẩy! 🪭",
    "Nhảy Gangnam Style vô tri cực đỉnh! 🐎",
    "Twerk Dance chọc mù mắt người xem! 🍑",
    "Hiphop Breakdance - Xoay đầu chấn động! 🤸",
    "Dab một phát bẻ cong mọi định luật vật lý! 🙅",
    "Shuffle Dance thần tốc, chân vô ảnh! 👟",
    "Pop Lock chấn động từng khớp xương! ⚡",
    "Điệu nhảy ăn mừng Thua Cuộc (Take the L)! 🇱",
    "Orange Justice Dance quạt tay điên cuồng! 🍊",
    "Xoay người Disco thập niên 80 rực rỡ! 🪩",
    "Nhảy Billie Jean xoay gót nhón chân! 🧦",
    "Waving tay dẻo kẹo như làn sóng biển! 🌊",
    "Nhảy Ma-ca-re-na khởi động khớp hông! 💃",

    // --- NHÓM 3: TUYỆT KỸ ANIME & PHIM ẢNH ---
    "Kamehamehaaa... Gồng siêu xay da! ⚡",
    "Chidori! Thiên điểu minh chấn! ⚡",
    "Triệu hồi thuật: Ngoại Đạo Ma Tượng! 👹",
    "Bật trạng thái Gear 5 - Nhảy tưng tưng! ☀️",
    "Lục Thức Hải Quân: Nguyệt Bộ bay vào! 🕊️",
    "Thuật Đa Trọng Ảnh Phân Thân! 👥",
    "Za Warudo! Ngưng đọng thời gian! ⏱️",
    "Thiên Chiếu! Ngọn lửa đen hủy diệt! 🔥",
    "Vô Hạn Bản Chất - Lĩnh vực triển khai! 🌌",
    "Gomu Gồng Liên Hoàn Đấm Máy Khâu! 👊",

    // --- NHÓM 4: GÁY KHÉT & CHỌC TỨC GAME THỦ ---
    "Chấp bạn một tay và nửa cây máu luôn! 🤫",
    "Trận này tôi thắng trong vòng 10 giây! ⏱️",
    "Bạn không có cửa chung mâm với ta đâu! 📉",
    "Gà mờ quá, về luyện thêm 10 năm đi! 🐔",
    "Chuẩn bị sẵn sàng nằm đo đất chưa? 🛌",
    "Nhìn kỹ bộ pháp ảo ma của ta đây! 👀",
    "Yếu thế này đấm không bõ dính răng! 🦷",
    "Né được một chiêu của ta, cho 10 tỷ! 💸",
    "Trọng tài ơi chuẩn bị sẵn cáng cứu thương! 🚑",
    "Đánh nhanh thắng nhanh còn về ăn cơm vợ nấu! 🍚",
    "Sát thương của bạn chỉ như muỗi gãi ngứa! 🦟",
    "Đứng im chịu trận đi cho đỡ đau đớn! 🛑",
    "Tuổi trẻ chưa trải sự đời rồi bạn ơi! 🍼",
    "Xin nhẹ cái đầu và chuỗi thắng của bạn nhé! 🎯",
    "Đấm phát này bay màu khỏi bản đồ luôn! 🎨",
    "Nhìn cái gì? Nhào vô đây ăn đấm! 💢",
    "Hạ gục được ta đi rồi hãy gáy nhé! 🥇",
    "Trận này tôi bật Auto-bot cũng thắng! 🤖",
    "Bạn đánh như tập dưỡng sinh buổi sáng vậy! 👵",
    "Đấu với ta là sai lầm lớn nhất đời bạn! 💀",
    "Sức mạnh này... Cảm giác thật vô đối! 🌌",
    "Né đòn đỉnh cao, không trúng một vết xước! 🛡️",
    "Bạn chỉ là một quân tốt thí trên bàn cờ thôi! ♟️",
    "Một phát Nhất Kiếm Tất Sát tiễn bạn lên đường! 🗡️",
    "Hào quang nhân vật chính phát sáng chói lòa! ✨",
    "Hôm nay ai cho bạn gan gạ kèo sinh tử với ta? 🌋",
    "Không cần vũ khí, nắm đấm này là đủ rồi! 👊",
    "Vừa ngủ vừa đánh cũng thắng được bạn! 💤",
    "Đừng khóc nhè khi bị ta hất tung lên trời nhé! 😭",
    "Tuyệt vọng đi! Đối thủ của bạn là thần thánh! ⛩️",
    "Thần linh cũng không cứu được bạn trận này! 🌌",
    "Bao nhiêu người như bạn cũng chỉ làm nền thôi! 🎞️",
    "Chuẩn bị nếm mùi vị của nỗi đau tột cùng! 🩸",
    "Chiến thắng đã được định đoạt từ lúc bắt đầu! 👑",
    "Xem ta biểu diễn nghệ thuật bạo lực đây! 🎬"
];
